### ISSUE TITLE
Requesting attachments of documents

### ISSUE THREAD

**Issue by spmraja** [spmselva/Whatsssup_Development#7]
Dear SPMSelva,
![lockdownclinic](https://user-images.githubusercontent.com/64902322/81293992-d82e7a80-908b-11ea-92f3-caafadc7d62b.jpeg)

It would be great if your app is capable of attaching the documents as well. Kindly add this feature. @

**Comment by spmselva** [comment]
Dear SPMRaja,

Thanks for your suggestion.

i am working on this and will fix soon.

**Comment by spmselva** [comment]
Thanks for suggestion. This feature is going to make our product great.
